#配置端口
server:
   port: 8088
   
#配置数据源
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/zblog
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: a
   resources:
      static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:D:/socket/imagsforblog/

#静态资源映射配置
web:
   upload-path: D:/socket/imagsforblog/

springboot :
   mvc: 
     static-path-parttern: /**
               
#日志配置
logging:
   level:
      com:
         zhi:
           zblog:
               dao: debug
               web: warn
               

     



